name: CloudMart IAM Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'cloudformation/iam-stack.yaml'
      - '.github/workflows/deploy-iam.yaml'

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  ENVIRONMENT: dev
  IAM_STACK_NAME: cloudmart-iam-dev

jobs:

  deploy-iam:

    name: Deploy IAM Stack

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}


      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity


      - name: Validate IAM CloudFormation template
        run: |
          aws cloudformation validate-template \
            --template-body file://cloudformation/iam-stack.yaml


      - name: Deploy IAM Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/iam-stack.yaml \
            --stack-name "$IAM_STACK_NAME" \
            --parameter-overrides \
              Environment="$ENVIRONMENT" \
            --capabilities CAPABILITY_NAMED_IAM


      - name: Wait for IAM Stack
        run: |
          aws cloudformation wait stack-create-complete \
            --stack-name "$IAM_STACK_NAME" || \
          aws cloudformation wait stack-update-complete \
            --stack-name "$IAM_STACK_NAME"


      - name: Show IAM Stack Status
        run: |
          aws cloudformation describe-stacks \
            --stack-name "$IAM_STACK_NAME" \
            --query 'Stacks[0].[StackName,StackStatus]' \
            --output table


      - name: Show IAM Stack Outputs
        run: |
          aws cloudformation describe-stacks \
            --stack-name "$IAM_STACK_NAME" \
            --query 'Stacks[0].Outputs' \
            --output table